Repository Feralape/Helmsguard, pull requests merged in 2024-11, with the labels that each got.

#17 Sundmark Update
  _maps/map_files/helmsguard/sundmark.dmm
  modular_helmsguard/code/game/turfs/open/floor/roguefloor.dm
Labels: Mapping

#20 Sundmark JSON change, more tavern work.
  _maps/map_files/helmsguard/sundmark.dmm
  _maps/sundmark.json
Labels: Mapping

#26 Small stuff
  code/__DEFINES/jobs.dm
  code/datums/skills/combat.dm
  code/game/objects/effects/landmarks.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/jobs/job_types/roguetown/garrison/arquebusier.dm
  code/modules/jobs/jobs.dm
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/head.dmi
  modular_helmsguard/code/game/objects/weapons/ranged/arquebus.dm
  roguetown.dme
Labels: Spriting, Balance

#30 More things
  code/modules/clothing/rogueclothes/ammopouch.dm
  code/modules/jobs/job_types/roguetown/garrison/arquebusier.dm
  code/modules/mob/living/simple_animal/rogue/rogueanimals.dm
  modular_helmsguard/code/game/objects/weapons/ranged/arquebus.dm
  modular_helmsguard/sound/arquebus/fuse.ogg
Labels: Balance

#34 castle
  _maps/map_files/helmsguard/sundmark.dmm
Labels: Mapping

#39 Sundmark
  _maps/map_files/helmsguard/sundmark.dmm
Labels: Mapping

#42 - added spawners to map for testing
  _maps/map_files/helmsguard/sundmark.dmm
  code/modules/mob/living/carbon/human/npc/_npc.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  modular_helmsguard/code/game/objects/structures/mob_spawner.dm
  modular_helmsguard/code/game/objects/structures/mobspawners/monster_spawner.dm
  modular_helmsguard/code/game/objects/structures/mobspawners/orcs_spawner.dm
  modular_helmsguard/code/game/objects/structures/mobspawners/undead_spawner.dm
  modular_helmsguard/icons/obj/structure/orc_banner.dmi
  modular_helmsguard/icons/obj/structure/spawners.dmi
  sound/foley/break_stone.ogg
Labels: Mapping
